[SR-237][build-script] Determine CMake in Python
SR-237 calls for `build-script` and `build-script-impl` to be merged. This
commit takes another step towards that goal by moving the logic that finds
the path to the CMake executable up into `build-script`.

Users of `build-script` were previously able to specify which CMake
they wished to use via `build-script-impl` args, like so:

```
$ utils/build-script -- --cmake=/foo/bar/cmake
```

This commit preserves that behavior, while also allowing users to
specify that path via `build-script` args:

```
$ utils/build-script --cmake=/baz/cmake -- --other --flags
```

diff --git a/utils/build-script-impl b/utils/build-script-impl
--- a/utils/build-script-impl
+++ b/utils/build-script-impl
@@ -672,6 +672,19 @@ if [ ! -e "${WORKSPACE}" ] ; then
     exit 1
 fi
 
+# FIXME: HOST_CC and CMAKE are set, and their presence is validated by,
+#        utils/build-script. These checks are redundant, but must remain until
+#        build-script-impl is merged completely with utils/build-script.
+#        For additional information, see: https://bugs.swift.org/browse/SR-237
+if [ -z "${HOST_CC}" ] ; then
+    echo "Can't find clang.  Please install clang-3.5 or a later version."
+    exit 1
+fi
+if [ -z "${CMAKE}" ] ; then
+    echo "Environment variable CMAKE must be specified."
+    exit 1
+fi
+
 function xcrun_find_tool() {
   xcrun --sdk macosx --toolchain "${DARWIN_XCRUN_TOOLCHAIN}" --find "$@"
 }
@@ -700,14 +713,6 @@ function true_false() {
 #
 # Set default values for command-line parameters.
 #
-
-if [[ "${CMAKE}" == "" ]] ; then
-    if [[ "$(uname -s)" == "Darwin" ]] ; then
-        CMAKE="$(xcrun_find_tool cmake)"
-    else
-        CMAKE="$(which cmake || echo /usr/local/bin/cmake)"
-    fi
-fi
 
 if [[ "${INSTALL_PREFIX}" == "" ]] ; then
     if [[ "$(uname -s)" == "Darwin" ]] ; then
@@ -1037,15 +1042,6 @@ if [[ "${EXPORT_COMPILE_COMMANDS}" ]] ; then
         "${COMMON_CMAKE_OPTIONS[@]}"
         -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
     )
-fi
-
-# FIXME: HOST_CC is set and its presence is validated by utils/build-script.
-#        This check is redundant, but must remain until build-script-impl
-#        is merged completely with utils/build-script.
-#        For additional information, see: https://bugs.swift.org/browse/SR-237
-if [ -z "${HOST_CC}" ] ; then
-    echo "Can't find clang.  Please install clang-3.5 or a later version."
-    exit 1
 fi
 
 if [[ "${DISTCC}" ]] ; then
