Add support for swift-xcode-playground-support project

diff --git a/utils/build-script-impl b/utils/build-script-impl
--- a/utils/build-script-impl
+++ b/utils/build-script-impl
@@ -85,6 +85,8 @@ KNOWN_SETTINGS=(
     lldb-build-type             "Debug"          "the CMake build variant for LLDB"
     llbuild-build-type          "Debug"          "the CMake build variant for llbuild"
     foundation-build-type       "Debug"          "the build variant for Foundation"
+    playgroundlogger-build-type "Debug"          "the build variant for PlaygroundLogger"
+    playgroundsupport-build-type "Debug"         "the build variant for PlaygroundSupport"
     xctest-build-type           "Debug"          "the build variant for xctest"
     llbuild-enable-assertions   "1"              "enable assertions in llbuild"
     enable-asan                 ""               "enable Address Sanitizer"
@@ -127,6 +129,8 @@ KNOWN_SETTINGS=(
     skip-build-foundation       ""               "set to skip building foundation"
     skip-build-libdispatch      ""               "set to skip building libdispatch"
     skip-build-benchmarks       ""               "set to skip building Swift Benchmark Suite"
+    skip-build-playgroundlogger ""               "set to skip building PlaygroundLogger"
+    skip-build-playgroundsupport ""              "set to skip building PlaygroundSupport"
     skip-test-cmark             ""               "set to skip testing CommonMark"
     skip-test-lldb              ""               "set to skip testing lldb"
     skip-test-swift             ""               "set to skip testing Swift"
@@ -135,6 +139,8 @@ KNOWN_SETTINGS=(
     skip-test-xctest            ""               "set to skip testing xctest"
     skip-test-foundation        ""               "set to skip testing foundation"
     skip-test-libdispatch       ""               "set to skip testing libdispatch"
+    skip-test-playgroundlogger  ""               "set to skip testing PlaygroundLogger"
+    skip-test-playgroundsupport ""               "set to skip testing PlaygroundSupport"
     skip-test-linux             ""               "set to skip testing Swift stdlibs for Linux"
     skip-test-freebsd           ""               "set to skip testing Swift stdlibs for FreeBSD"
     skip-test-cygwin            ""               "set to skip testing Swift stdlibs for Cygwin"
@@ -184,6 +190,8 @@ KNOWN_SETTINGS=(
     install-xctest              ""               "whether to install xctest"
     install-foundation          ""               "whether to install foundation"
     install-libdispatch         ""               "whether to install libdispatch"
+    install-playgroundlogger    ""               "whether to install PlaygroundLogger"
+    install-playgroundsupport   ""               "whether to install PlaygroundSupport"
     darwin-install-extract-symbols ""            "whether to extract symbols with dsymutil during installations"
     host-target                 ""               "The host target. LLVM, Clang, and Swift will be built for this target. The built LLVM and Clang will be used to compile Swift for the cross-compilation targets. **This argument is required**"
     stdlib-deployment-targets   ""               "space-separated list of targets to configure the Swift standard library to be compiled or cross-compiled for"
@@ -390,6 +398,14 @@ function set_build_options_for_host() {
             case ${host} in
                 linux-x86_64)
                     SWIFT_HOST_VARIANT_ARCH="x86_64"
+                    playgroundlogger_build_cmd="${PLAYGROUNDLOGGER_SOURCE_DIR}/build.py"
+                    playgroundlogger_build_options=(
+                        --swiftc "$(build_directory_bin ${host} swift)"
+                        --foundation "$(build_directory ${host} foundation)"
+                        --build-dir "$(build_directory ${host} playgroundlogger)"
+                        --swift-build-dir "$(build_directory ${host} swift)"
+                        --`python -c 'import sys; print sys.argv[1].lower()' ${PLAYGROUNDLOGGER_BUILD_TYPE}`
+                    )
                     ;;
                 linux-armv6)
                     SWIFT_HOST_VARIANT_ARCH="armv6"
@@ -437,6 +453,9 @@ function set_build_options_for_host() {
                     swiftpm_bootstrap_options=(
                         --sysroot="$(xcrun --sdk ${xcrun_sdk_name} --show-sdk-path)"
                     )
+                    playgroundlogger_build_cmd="xcodebuild"
+                    playgroundlogger_build_target=("PlaygroundLogger_TestDriver")
+                    PLAYGROUNDLOGGER_INSTALL_PLATFORM="MacOSX.platform"
                     ;;
                 iphonesimulator-i386)
                     xcrun_sdk_name="iphonesimulator"
@@ -452,6 +471,9 @@ function set_build_options_for_host() {
                         -DCMAKE_CXX_FLAGS="$(cmark_c_flags ${host})"
                         -DCMAKE_OSX_SYSROOT:PATH="$(xcrun --sdk ${xcrun_sdk_name} --show-sdk-path)"
                     )
+                    playgroundlogger_build_cmd="xcodebuild"
+                    playgroundlogger_build_target=("PlaygroundLogger_iOS")
+                    PLAYGROUNDLOGGER_INSTALL_PLATFORM="iPhoneSimulator.platform"
                     ;;
                 iphonesimulator-x86_64)
                     xcrun_sdk_name="iphonesimulator"
@@ -467,6 +489,9 @@ function set_build_options_for_host() {
                         -DCMAKE_CXX_FLAGS="$(cmark_c_flags ${host})"
                         -DCMAKE_OSX_SYSROOT:PATH="$(xcrun --sdk ${xcrun_sdk_name} --show-sdk-path)"
                     )
+                    playgroundlogger_build_cmd="xcodebuild"
+                    playgroundlogger_build_target=("PlaygroundLogger_iOS")
+                    PLAYGROUNDLOGGER_INSTALL_PLATFORM="iPhoneSimulator.platform"
                     ;;
                 iphoneos-armv7)
                     xcrun_sdk_name="iphoneos"
@@ -482,6 +507,9 @@ function set_build_options_for_host() {
                         -DCMAKE_CXX_FLAGS="$(cmark_c_flags ${host})"
                         -DCMAKE_OSX_SYSROOT:PATH="$(xcrun --sdk ${xcrun_sdk_name} --show-sdk-path)"
                     )
+                    playgroundlogger_build_cmd="xcodebuild"
+                    playgroundlogger_build_target=("PlaygroundLogger_iOS")
+                    PLAYGROUNDLOGGER_INSTALL_PLATFORM="iPhoneOS.platform"
                     ;;
                 iphoneos-armv7s)
                     xcrun_sdk_name="iphoneos"
@@ -497,6 +525,9 @@ function set_build_options_for_host() {
                         -DCMAKE_CXX_FLAGS="$(cmark_c_flags ${host})"
                         -DCMAKE_OSX_SYSROOT:PATH="$(xcrun --sdk ${xcrun_sdk_name} --show-sdk-path)"
                     )
+                    playgroundlogger_build_cmd="xcodebuild"
+                    playgroundlogger_build_target=("PlaygroundLogger_iOS")
+                    PLAYGROUNDLOGGER_INSTALL_PLATFORM="iPhoneOS.platform"
                     ;;
                 iphoneos-arm64)
                     xcrun_sdk_name="iphoneos"
@@ -512,6 +543,9 @@ function set_build_options_for_host() {
                         -DCMAKE_CXX_FLAGS="$(cmark_c_flags ${host})"
                         -DCMAKE_OSX_SYSROOT:PATH="$(xcrun --sdk ${xcrun_sdk_name} --show-sdk-path)"
                     )
+                    playgroundlogger_build_cmd="xcodebuild"
+                    playgroundlogger_build_target=("PlaygroundLogger_iOS")
+                    PLAYGROUNDLOGGER_INSTALL_PLATFORM="iPhoneOS.platform"
                     ;;
                 appletvsimulator-x86_64)
                     xcrun_sdk_name="appletvsimulator"
@@ -527,6 +561,9 @@ function set_build_options_for_host() {
                         -DCMAKE_CXX_FLAGS="$(cmark_c_flags ${host})"
                         -DCMAKE_OSX_SYSROOT:PATH="$(xcrun --sdk ${xcrun_sdk_name} --show-sdk-path)"
                     )
+                    playgroundlogger_build_cmd="xcodebuild"
+                    playgroundlogger_build_target=("PlaygroundLogger_tvOS")
+                    PLAYGROUNDLOGGER_INSTALL_PLATFORM="AppleTVSimulator.platform"
                     ;;
                 appletvos-arm64)
                     xcrun_sdk_name="appletvos"
@@ -542,6 +579,9 @@ function set_build_options_for_host() {
                         -DCMAKE_CXX_FLAGS="$(cmark_c_flags ${host})"
                         -DCMAKE_OSX_SYSROOT:PATH="$(xcrun --sdk ${xcrun_sdk_name} --show-sdk-path)"
                     )
+                    playgroundlogger_build_cmd="xcodebuild"
+                    playgroundlogger_build_target=("PlaygroundLogger_tvOS")
+                    PLAYGROUNDLOGGER_INSTALL_PLATFORM="AppleTVOS.platform"
                     ;;
                 watchsimulator-i386)
                     xcrun_sdk_name="watchsimulator"
@@ -1086,6 +1126,8 @@ SWIFTPM_SOURCE_DIR="${WORKSPACE}/swiftpm"
 XCTEST_SOURCE_DIR="${WORKSPACE}/swift-corelibs-xctest"
 FOUNDATION_SOURCE_DIR="${WORKSPACE}/swift-corelibs-foundation"
 LIBDISPATCH_SOURCE_DIR="${WORKSPACE}/swift-corelibs-libdispatch"
+PLAYGROUNDLOGGER_SOURCE_DIR="${WORKSPACE}/swift-xcode-playground-support/PlaygroundLogger"
+PLAYGROUNDSUPPORT_SOURCE_DIR="${WORKSPACE}/swift-xcode-playground-support/PlaygroundSupport"
 
 if [[ ! -d ${CMARK_SOURCE_DIR} ]]; then
     echo "Couldn't find cmark source directory."
@@ -1114,6 +1156,16 @@ fi
 
 if [[ ! "${SKIP_BUILD_LIBDISPATCH}" && ! -d ${LIBDISPATCH_SOURCE_DIR} ]]; then
     echo "Couldn't find libdispatch source directory."
+    exit 1
+fi
+
+if [[ ! "${SKIP_BUILD_PLAYGROUNDLOGGER}" && ! -d ${PLAYGROUNDLOGGER_SOURCE_DIR} ]]; then
+    echo "Couldn't find PlaygroundLogger source directory."
+    exit 1
+fi
+
+if [[ ! "${SKIP_BUILD_PLAYGROUNDSUPPORT}" && ! -d ${PLAYGROUNDSUPPORT_SOURCE_DIR} ]]; then
+    echo "Couldn't find PlaygroundSupport source directory."
     exit 1
 fi
 
@@ -1152,6 +1204,12 @@ fi
 # added to the list of build products first.
 if [[ ! "${SKIP_BUILD_FOUNDATION}" ]] ; then
      PRODUCTS=("${PRODUCTS[@]}" foundation)
+fi
+if [[ ! "${SKIP_BUILD_PLAYGROUNDLOGGER}" ]] ; then
+     PRODUCTS=("${PRODUCTS[@]}" playgroundlogger)
+fi
+if [[ ! "${SKIP_BUILD_PLAYGROUNDSUPPORT}" ]] ; then
+     PRODUCTS=("${PRODUCTS[@]}" playgroundsupport)
 fi
 # SwiftPM is dependent on XCTest, so XCTest must be added to the list of
 # build products first.
@@ -1414,6 +1472,13 @@ function build_directory_bin() {
             libdispatch)
                 echo "${root}/bin"
                 ;;
+            playgroundlogger)
+                # FIXME: var name for build type
+                echo "${root}/${PLAYGROUNDLOGGER_BUILD_TYPE}/bin"
+                ;;
+            playgroundsupport)
+                echo "${root}/${PLAYGROUNDSUPPORT_BUILD_TYPE}/bin"
+                ;;
             *)
                 echo "error: unknown product: ${product}"
                 exit 1
@@ -1524,6 +1589,13 @@ function cmake_config_opt() {
                 echo "--config ${FOUNDATION_BUILD_TYPE}"
                 ;;            
             libdispatch)
+                ;;
+            playgroundlogger)
+                # FIXME: var name
+                echo "--config ${PLAYGROUNDLOGGER_BUILD_TYPE}"
+                ;;
+            playgroundsupport)
+                echo "--config ${PLAYGROUNDSUPPORT_BUILD_TYPE}"
                 ;;
             *)
                 echo "error: unknown product: ${product}"
@@ -2203,6 +2275,30 @@ for host in "${ALL_HOSTS[@]}"; do
                 # libdispatch builds itself and doesn't use cmake
                 continue
                 ;;
+            playgroundlogger)
+                PLAYGROUNDLOGGER_BUILD_DIR=$(build_directory ${host} ${product})
+                SWIFTC_BIN="$(build_directory_bin ${host} swift)/swiftc"
+
+                set -x
+                pushd "${PLAYGROUNDLOGGER_SOURCE_DIR}"
+                mkdir -p "${PLAYGROUNDLOGGER_BUILD_DIR}"
+                "${playgroundlogger_build_cmd}" -configuration "${PLAYGROUNDLOGGER_BUILD_TYPE}" -target "${playgroundlogger_build_target}" install SWIFT_EXEC="${SWIFTC_BIN}" DSTROOT=${build_dir} INSTALL_PATH="/" SKIP_INSTALL=NO
+                popd
+                { set +x; } 2>/dev/null
+                continue
+                ;;
+            playgroundsupport)
+                PLAYGROUNDSUPPORT_BUILD_DIR=$(build_directory ${host} ${product})
+                SWIFTC_BIN="$(build_directory_bin ${host} swift)/swiftc"
+
+                set -x
+                pushd "${PLAYGROUNDSUPPORT_SOURCE_DIR}"
+                mkdir -p "${PLAYGROUNDSUPPORT_BUILD_DIR}"
+                "xcodebuild" -configuration "${PLAYGROUNDSUPPORT_BUILD_TYPE}" -target AllProducts SWIFT_EXEC="${SWIFTC_BIN}" DSTROOT="$(get_host_install_destdir ${host})"
+                popd
+                { set +x; } 2>/dev/null
+                continue
+                ;;
             *)
                 echo "error: unknown product: ${product}"
                 exit 1
@@ -2472,6 +2568,19 @@ for host in "${ALL_HOSTS[@]}"; do
                 echo "--- Finished tests for ${product} ---"
                 continue
                 ;;
+           playgroundlogger)
+               SWIFT_DYLIB_PATH=$(build_directory ${host} swift)/lib/swift/macosx/
+               PLAYGROUNDLOGGER_FRAMEWORK_PATH=$(build_directory ${host} ${product})
+               set -x
+               pushd "${PLAYGROUNDLOGGER_FRAMEWORK_PATH}"
+               DYLD_LIBRARY_PATH=$SWIFT_DYLIB_PATH DYLD_FRAMEWORK_PATH=$PLAYGROUNDLOGGER_FRAMEWORK_PATH ./PlaygroundLogger_TestDriver
+               popd
+               { set +x; } 2>/dev/null
+               continue
+               ;;
+           playgroundsupport)
+               continue
+               ;;
             *)
                 echo "error: unknown product: ${product}"
                 exit 1
@@ -2688,6 +2797,64 @@ for host in "${ALL_HOSTS[@]}"; do
 
                 # As libdispatch installation is self-contained, we break early here.
                 continue
+                ;;
+            playgroundlogger)
+                if [[ -z "${INSTALL_PLAYGROUNDLOGGER}" ]] ; then
+                    continue
+                fi
+                if [[ -z "${INSTALL_DESTDIR}" ]] ; then
+                    echo "--install-destdir is required to install products."
+                    exit 1
+                fi
+
+                echo "--- Installing ${product} ---"
+                PLAYGROUNDLOGGER_BUILD_DIR=$(build_directory ${host} playgroundlogger)
+                PLAYGROUNDLOGGER_INSTALL_PREFIX="${INSTALL_DESTDIR}"
+                # Note that installing directly to /usr/lib/swift usually
+                # requires root permissions.
+                set -x
+                case "$(uname -s)" in
+                    Linux)
+                        PLAYGROUNDLOGGER_INSTALL_DIR="$(get_host_install_destdir ${host})/$(get_host_install_prefix ${host})/lib/swift/linux"
+                        mkdir -p "${PLAYGROUNDLOGGER_INSTALL_DIR}"
+                        cp -R "${PLAYGROUNDLOGGER_BUILD_DIR}"/libPlaygroundLogger.so "${PLAYGROUNDLOGGER_INSTALL_DIR}"
+                        ;;
+                    Darwin)
+                        pushd "${PLAYGROUNDLOGGER_SOURCE_DIR}"
+                        xcodebuild -target "All Platforms Logger" -configuration Toolchain_${PLAYGROUNDLOGGER_BUILD_TYPE} install SWIFT_EXEC="${SWIFTC_BIN}" DT_TOOLCHAIN_DIR="${TOOLCHAIN_PREFIX}" DSTROOT="$(get_host_install_destdir ${host})"
+                        popd
+                        continue
+                        ;;
+                    *)
+                        echo "error: --install-playgroundlogger is not supported on this platform"
+                        exit 1
+                        ;;
+                esac
+                { set +x; } 2>/dev/null
+
+                # As XCTest installation is self-contained, we break early here.
+                continue
+                ;;
+            playgroundsupport)
+                set -x
+                if [[ -z "${INSTALL_PLAYGROUNDSUPPORT}" ]] ; then
+                    continue
+                fi
+                case "$(uname -s)" in
+                    Linux)
+                        ;;
+                    FreeBSD)
+                        ;;
+                    CYGWIN_NT-10.0)
+                        ;;
+                    Darwin)
+                        pushd "${PLAYGROUNDSUPPORT_SOURCE_DIR}"
+                        xcodebuild -target AllProducts -configuration ${PLAYGROUNDSUPPORT_BUILD_TYPE} install SWIFT_EXEC="${SWIFTC_BIN}" DT_TOOLCHAIN_DIR="${TOOLCHAIN_PREFIX}" DSTROOT="$(get_host_install_destdir ${host})"
+                        popd
+                        continue
+                        ;;
+                esac
+                { set +x; } 2>/dev/null
                 ;;
             *)
                 echo "error: unknown product: ${product}"
