[Build-script] Add logic to find clang install with not default name

diff --git a/utils/build-script-impl b/utils/build-script-impl
--- a/utils/build-script-impl
+++ b/utils/build-script-impl
@@ -986,9 +986,18 @@ if [ -z "${HOST_CC}" ] ; then
         HOST_CC="$(xcrun_find_tool clang)"
         HOST_CXX="$(xcrun_find_tool clang++)"
     else
-        HOST_CC="clang"
-        HOST_CXX="clang++"
+        for clang_candidate_suffix in "" "-3.8" "-3.7" "-3.6" "-3.5" ; do
+            if which "clang${clang_candidate_suffix}" > /dev/null ; then
+                HOST_CC="clang${clang_candidate_suffix}"
+                HOST_CXX="clang++${clang_candidate_suffix}"
+                break
+            fi
+        done
     fi
+fi
+if [ -z "${HOST_CC}" ] ; then
+    echo "Can't find clang.  Please install clang-3.5 or a later version."
+    exit 1
 fi
 
 if [[ "$DISTCC" ]] ; then
