build-script: don't run 'git', we have update-checkout for that

diff --git a/utils/build-script-impl b/utils/build-script-impl
--- a/utils/build-script-impl
+++ b/utils/build-script-impl
@@ -856,10 +856,8 @@ XCTEST_SOURCE_DIR="$WORKSPACE/swift-corelibs-xctest"
 FOUNDATION_SOURCE_DIR="$WORKSPACE/swift-corelibs-foundation"
 
 if [[ ! -d $CMARK_SOURCE_DIR ]]; then
-  echo "$CMARK_SOURCE_DIR not found. Attempting to clone ..."
-  git clone https://github.com/apple/swift-cmark.git "$CMARK_SOURCE_DIR" || \
-    (echo "Couldn't clone cmark. Please check README.md and visit https://github.com/apple/swift-cmark for details." && \
-    exit 1)
+    echo "Couldn't find cmark source directory."
+    exit 1
 fi
 
 # Migration code for the cmark repository.  Can be removed in February 2016.
